[connections.mysql]
dialect = "mysql"
driver = "pymysql"
host = "mysql-aef5a3f-insy661-airbnb.aivencloud.com"
port = 17389
database = "insy661"
username = "avnadmin"
password = "AVNS_o16_GWpWBDbNPkA0x_t"